### ISSUE TITLE
Version on PyPi one lower than releases on Github

### ISSUE THREAD

**Issue by mvdwetering** [MatthewFlamm/pytest-homeassistant-custom-component#19]
It seems that the version number of the packages on PyPi are 1 lower than the releases on Github which is a bit confusing. Not sure if it is an error or just how stuff works.

For example, right now I see latest release on Github is 0.0.18 made on November 8th. On PyPi I see latest release 0.0.17 also on November 8th. I am pretty sure these are the same.

When looking at the publish action "Upload Python Package" with the title "Release 0.0.18" I see that in the `deploy/Build and publish` step it says 0.0.17, so it looks like somehow the version it takes is wrong/old or maybe the version gets updated after the release is made.

**Comment by MatthewFlamm** [comment]
Thank you!  I can confirm this behavior.  It looks like the tags and release are created correctly.  It also looks like the publish action works but it doesn't see the updated git info.

I think that this is caused by having two actions to do these two pieces.  The first action creates the release which triggers the publish.  The git info doesn't sync until the first action completes.

One potential solution is to combine these actions.

**Comment by MatthewFlamm** [comment]
Thanks for this report again!  I combined the actions and now everything works great.  0.0.19 should be identical to v0.0.18 (except for the version number) so even though PyPI is now missing 0.0.18, it is functionally complete.
