### ISSUE TITLE
Update component to use non beta releases

### ISSUE THREAD

**Issue by iMicknl** [MatthewFlamm/pytest-homeassistant-custom-component#88]
Thanks for providing this pytest component. We do use this for https://github.com/iMicknl/ha-tahoma, however this component doesn't have a release for the final release, only for the b0 version.

Are you planning to (automatically) release versions for every HA version released.

```
pytest-homeassistant-custom-component 0.4.6 requires homeassistant==2021.11.0b0, but you'll have homeassistant 2021.11.0 which is incompatible.
```

**Comment by MatthewFlamm** [comment]
Thanks for the question.  I would _hope_ that homeassistant doesn't introduce changes to their testing plugins during a beta period, but it has happened infrequently.  I just updated the automated pull request and there are not changes to the testing plugins in 2021.11.0 compared to the 2021.11.0b0.  See #87.  We didn't always pin the version of homeassistant, but this was worse IMO since it broke testing unexpectedly and was very annoying.

It is really limited to my time and availability to be making multiple releases over a week or so.  One could also argue that we might need to release for every full patch release as well (it is possible that testing might change if a significant bug is fixed).  I do make an effort to get at least 1 release per beta cycle, as I think these are the most important to enable custom component developers to check for compatibility before it is released as a full minor release.

This is a really hard problem, because there are changes in homeassistant that require manual changes here.  I think the current state is relatively stable, albeit it is not always strongly coupled with homeassistant releases.  If we implement #59, this would bring more flexibility, e.g. you could set up your CI to run against the latest homeassistant tag ref or the latest dev branch commit.  But if any change in homeassistant testing requires a manual change here, it will break hard.  I think this is probably the best halfway ground here though.  To enable usage of a CLI for more recent versions of homeassistant, but knowing that this is prone to fail at any minute.

**Comment by MatthewFlamm** [comment]
Another option is to implement #7. We would check for new versions every day and automatically release versions when they pass the minimal CI here.  This would put one more check in place to ensure that users of this package don't have failing tests before their own testing.  Maybe this is better?

**Comment by iMicknl** [comment]
@MatthewFlamm first of all, many thanks for this component. I wasn't aware that you pushed the changes manually. I am happy to have a look if we can automate this via GitHub Actions.

Perhaps it would make sense as well to change the version number to match Home Assistants, especially since the version is pinned. In my custom component, we also pin the Home Assistant version separately and I like to use the stable for that one, hence my request.

**Comment by MatthewFlamm** [comment]
@iMicknl I am really close to having all the needed components for automatic releasing on some schedule, probably daily? See #91. The last piece that I think needs to be addressed is alignment on versions.

> Perhaps it would make sense as well to change the version number to match Home Assistants, especially since the version is pinned.

This is an ideal state, but I'm worried about the following situation:  An automatic release is made that aligns with a homeassistant version, for example 2021.12.0.  It is found out that we should have modified the extraction in some way before the release.  What do we do?  I'd have to re-release 2021.12.0 for this package after manually editing it.  This is a lot of maintenance burden.  It also doesn't make it clear which versions of this package are compatible for extracting testing utilities from which versions of homeassistant.

The current versioning system has the following logic:

- All patch releases are from automatic releases
- All minor releases are due to changes in extraction <- this allows us to trace back compatability for a future CLI #59 

Some musings
- We have one more version specifier available that could help here.
- We could consider using the homeassistant version in the patch (and promote the version specifiers above to major/minor)
- We would have to come up with some method of squashing the homeassistant version
- If we squash it with 0 padding, it would look something like 1.4.20210501 or 1.3.20210500b0
- This would allow this project to fix releases by releasing 1.5.20210501 for example.
- This doesn't really seem all the usable however.  It is more of a pointer to the user, but this is already available in the package.

I strongly lean to keep the current state, unless you have any suggestions.  This can also be figured out in a future PR.

**Comment by MatthewFlamm** [comment]
One more point is that this version already pins homeassistant as a requirement, why are you also installing it separately?

**Comment by iMicknl** [comment]
Thanks for your extensive reply, I will have a look at it this weekend and see if I can come up with any ideas.

> One more point is that this version already pins homeassistant as a requirement, why are you also installing it separately?

Maybe it is overkill indeed, but we separated our requirements.txt in 3 files:
- [requirements.txt](https://github.com/iMicknl/ha-tahoma/blob/master/requirements.txt)
- [requirements_dev.txt](https://github.com/iMicknl/ha-tahoma/blob/master/requirements_dev.txt)
- [requirements_test.txt](https://github.com/iMicknl/ha-tahoma/blob/master/requirements_test.txt)

We did this to have a clear overview what is required to run the integration, what is required for autocomplete/typing during development and what is required to run the test. Happy to hear your opinion on a better strategy as well.

**Comment by MatthewFlamm** [comment]
Definitely needs some more thinking before changing course.  I'm going to open a new issue to collect thoughts on this.  See #92.

**Comment by MatthewFlamm** [comment]
Meant to autoclose this with #91
